# Generated by Django 4.1.5 on 2023-03-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_enroll_no'),
        ('users', '0004_message_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='message',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorprofile'),
        ),
    ]
