# Generated by Django 4.1.5 on 2023-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_message_doctor_id_message_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
