# Generated by Django 4.1.5 on 2023-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='Enroll_No',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
